config/routes.rb
Rails.application.routes.draw do

  root 'runs#index'

  get   'runs/graph_data'             => 'runs#graph_data',         as: 'graph_data'

  get   'runs/load_from_mmf'          => 'runs#load_from_mmf'
  get   'runs/:id/targets/link'       => 'runs#new_link',           as: 'new_link'
  post  'runs/:id/targets/link'       => 'runs#link_to_target',     as: 'link_to_target'
  post  'runs/:id/targets/api_link'   => 'runs#api_link_to_target', as: 'api_link_to_target'

  resources :runs 
  resources :run_targets

end

app/models/workouts/run.rb
class Run < Workout

  validates :pace,  presence:             { message: Proc.new{ presence_msg(:pace)            } }
  validates :pace,  numericality:         { message: Proc.new{ numeric_msg(:pace)             } }

  validates :distance,  presence:         { message: Proc.new{ presence_msg(:distance)        } }
  validates :distance,  numericality:     { message: Proc.new{ numeric_msg(:distance)         } }

  validates :pace_metric, presence:       { message: Proc.new{ presence_msg(:pace_metric)     } }            
  validates :pace_metric, inclusion:      { in: ApplicationSettings.config['pace_metrics'] , 
                                            message: Proc.new{ metric_content_msg(:pace)      } }

  validates :distance_metric, presence:   { message: Proc.new{ presence_msg(:distance_metric) } }            
  validates :distance_metric, inclusion:  { in: ApplicationSettings.config['distance_metrics'] , 
                                            message: Proc.new{ metric_content_msg(:distance)  } }                                      
                                   

  def flash_error
    errors.messages.map{ |msg_key, msg_val| "Error: #{msg_val.join(',')}\n" }.join('')
  end

  class << self

    def create_from(params)
      create(params[:run].permit(attributes))
    end

    def update_from(params)
      find(params[:id]).update(params[:run].permit(attributes))
    end

    def generate_coordinates
      self.all.map{ |run| [run.date.to_time.to_i * 1000, run.pace.to_f] }
    end

    private

    def attributes
      [
        :activity, 
        :date, 
        :duration, 
        :intensity,
        :pace,
        :pace_metric,
        :distance,
        :distance_metric
      ]
    end

  end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

  MMF = MMFDataLoader.new

  def index
    @runs =         Run.all.reverse
    @run_targets =  RunTarget.all.reverse

    if @runs.any?
      RunAnalyzer.set_benchmark_from(@runs)
      TrainingPace.set_training_paces_using(RunAnalyzer)
      @training_paces = TrainingPace.all
    end
    
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.create_from(params)
    
    if @run.save
      redirect_to(runs_path)
    else 
      flash[:error] = @run.flash_error
      render :new
    end

  end

  def edit
    @run = Run.find(params[:id])
  end

  def update
    @run = Run.update_from(params)
    
    if @run
      redirect_to(runs_path)
    else  
      flash[:error] = @run.flash_error
      render :edit
    end
    
  end

  def destroy
    Run.find(params[:id]).delete
    redirect_to runs_path
  end

  def load_from_mmf
    MMF.save_my_workouts_to_db
    redirect_to runs_path
  end

  def new_link
    @run = Run.find(params[:id])
    @run_targets = RunTarget.all
  end

  def link_to_target
    Target.link_workout(params)
    redirect_to runs_path
  end

  def api_link_to_target
    Target.link_workout(params)
    render json: { status: 'OK'}
  end

  def graph_data
    render json: Run.generate_coordinates
  end

end

app/views/runs/_form.html.erb
<%= form_for(run) do |f| %>
  
  <table>

    <tr>
      <td><%= f.label :activity %></td>
      <td><%= f.text_field :activity %></td>
    </tr>
    <tr>
      <td><%= f.label :date %></td>
      <td><%= f.text_field :date %></td>
    </tr>
    <tr>
      <td><%= f.label :duration %></td>
      <td><%= f.text_field :duration %></td>
    </tr>
    <tr>
      <td><%= f.label :intensity %></td>
      <td><%= f.text_field :intensity %></td>
    </tr>
    <tr>
      <td><%= f.label :pace %></td>
      <td><%= f.text_field :pace %></td>
    </tr>
    <tr>
      <td><%= f.label :pace_metric %></td>
      <td><%= f.text_field :pace_metric %></td>
    </tr>
    <tr>
      <td><%= f.label :distance %></td>
      <td><%= f.text_field :distance %></td>
    </tr>
    <tr>
      <td><%= f.label :distance_metric %></td>
      <td><%= f.text_field :distance_metric %></td>
    </tr>

  </table>

  <%= f.submit btn_description %>
  
<% end %>

app/views/runs/_run.html.erb
<article class='run panel panel-default'>

    <section class='run_details panel-body'>
      <i class="fa fa-star"></i>
      <table class='run_table'>
        <tr>
          <td><%= run.activity %></td>
          <td><%= run.date %></td>
        </tr>
        <tr>
          <td><%= run.duration %></td>
          <td><%= run.intensity %></td>
        </tr>
        <tr>
          <td><%= run.pace %><%= run.pace_metric %></td>
          <td><%= run.distance %><%= run.distance_metric %></td>
        </tr>
        <tr class='hidden'>
          <td class='run_id'><%= run.id %></td>
        </tr>
      </table>
    </section>

    <nav class='workout_nav panel-footer'>

      <%= link_to 'Link to Target', new_link_path(run) %> | 
      <%= link_to 'Edit', edit_run_path(run) %> | 
      <%= link_to 'Delete', run_path(run), method: :delete %>

    </nav>

</article>

app/views/runs/edit.html.erb
<%= render partial: 'form', locals: {run: @run, btn_description: 'Update'} %>

app/views/runs/index.html.erb
<section class='data col-md-6'>

  <article class='main_graph col-md-12'>
      <h3>
        <i class="fa fa-area-chart"></i>
        Performance
      </h3>

      <div id="placeholder"></div>
  </article>

  <article class='workouts_list col-md-12'>
      <% if @runs.any? %>
       
        <header class='run_header'>
          <h3>
            <span class="glyphicon glyphicon-signal"></span>
            Runs
          </h3>
        </header>

        <div class='run_container'>
          <%= render @runs %>
        </div>

      <% else %>
        <h3>No workouts yet - shape up!</h3>
      <% end %>
  </article>

</section>

<aside class='helpers col-md-6'>

  <article class='targets_list col-md-6'>
    <%= render 'run_targets/targets' %>
  </article>

  <article class='training_pace col-md-6'>
    <%= render 'training_paces/index' %>
  </article>

</aside>

app/views/runs/new.html.erb
<%= render partial: 'form', locals: {run: @run, btn_description: 'Add'} %>

app/views/runs/new_link.html.erb
<%= form_tag do |f|%>

  <%= collection_select(:workout, :targets, @run_targets, :id, :description, {}, {id: 'target_selector'}) %></br>
  <%= submit_tag 'Link' %>

<% end %>