config/routes.rb
Rails.application.routes.draw do

  root 'runs#index'

  get   'runs/graph_data'             => 'runs#graph_data',         as: 'graph_data'

  get   'runs/load_from_mmf'          => 'runs#load_from_mmf'
  get   'runs/:id/targets/link'       => 'runs#new_link',           as: 'new_link'
  post  'runs/:id/targets/link'       => 'runs#link_to_target',     as: 'link_to_target'
  post  'runs/:id/targets/api_link'   => 'runs#api_link_to_target', as: 'api_link_to_target'

  resources :runs 
  resources :run_targets

end

app/views/layouts/_messages.html.erb
<% if flash[:error] %>
  <h3 class='error_msg'><%= flash[:error] %></h3>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <section class="container">
   
    <header class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-road"></span>
        iMapMyLife
      </a>

    </header>

    <aside class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_run_path do %>
            <span class="glyphicon glyphicon-plus"></span>
            New Workout
          <% end %>
        </li>
        <li>
          <%= link_to  runs_load_from_mmf_path, id: 'load_mmf_data' do %>
            <span class="glyphicon glyphicon-cloud-download"></span>
            Load from MMF
          <% end %>
        </li>
        <li>
          <%= link_to new_run_target_path do %>
            <span class="glyphicon glyphicon-screenshot"></span>
            Add Target
          <% end %>
        </li>
      </ul>
    </aside><!--/.navbar-collapse -->

  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapMyLife</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
  </header>

  <main class='container'>
    <%= yield %>
  </main>

</body>
</html>